using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LearnOnline.Models
{
    // Class entity – a single scheduled class session within a timetable
    // Represents a recurring slot (e.g. "Monday 09:00-11:00 in Room 208")
    public class Class
    {
        [Key]
        public string Id { get; set; } = Guid.NewGuid().ToString();

        // Foreign key to the Timetable this class belongs to
        [Required]
        public string TimetableId { get; set; } = null!;

        [ForeignKey("TimetableId")]
        public Timetable? Timetable { get; set; }

        // Foreign key to the Course being taught in this slot
        [Required]
        public string CourseId { get; set; } = null!;

        [ForeignKey("CourseId")]
        public Course? Course { get; set; }

        // Physical or virtual room name
        public string? Room { get; set; }

        // Day of the week (e.g. "Monday")
        public string? DayOfWeek { get; set; }

        // Start and end times for the class slot
        public TimeOnly? StartTime { get; set; }
        public TimeOnly? EndTime { get; set; }

        // Whether this slot was auto-generated by the timetable engine
        public bool IsGenerated { get; set; } = false;
    }
}
